# Generated by Django 4.2 on 2023-08-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaTex',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('katex', models.TextField(help_text='Read more about KaTeX formulae in <a href="https://katex.org" target="_blank">its documentation</a>', verbose_name='Formula')),
                ('katex_display_style', models.SmallIntegerField(choices=[(0, 'Inline style'), (1, 'Display style'), (2, 'Display style flush left')], default=1, help_text='Switch between inline and display style', verbose_name='Style')),
            ],
            options={
                'verbose_name': 'KaTeX Formula',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
