# Generated by Django 4.2.4 on 2023-08-18 15:47

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaTex',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('katex', models.TextField(verbose_name='Formula')),
                ('katex_display_style', models.BooleanField(choices=[(False, 'Inline style'), (True, 'Display style')], help_text='Switch between inline and display style', verbose_name='Style', default=True, null=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'verbose_name': 'KaTeX Formula',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
