# Generated by Django 5.0.3 on 2024-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_katex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="katex",
            name="katex_display_style",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Inline style"),
                    (1, "Display style"),
                    (2, "Display style flush left"),
                ],
                default=1,
                help_text="Switch between styles",
                verbose_name="Style",
            ),
        ),
    ]
